---
version: "3.0"
services:
  arch_mirror:
    image: themadmaker2/arch_mirror:latest
    container_name: arch_mirror
    environment:
      - TZ=America/New_York
    ports:
      - 80:80
    volumes:
      - Storage:/data
    restart: unless-stopped
